export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',
  RESERVATION_NOT_AVAILABLE: 'RESERVATION_NOT_AVAILABLE',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  DUPLICATED_RESOURCE: 'DUPLICATED_RESOURCE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
